### ISSUE TITLE
Tampilan Login

### ISSUE THREAD

**Issue by Dikry720p** [perpustakaan-23/E-PERPUS#3]
![Image](https://github.com/perpustakaan-23/E-PERPUS/assets/132629095/41773f1a-b0bb-4432-8ca0-733c59c76abf)

**Tampilan Login** 

Gambar Background Ukuran Width 1512 x 982 Height 
Rectangle 1 : 	Uk. 859x159 (Radius 15)
                       Color : Biru Kode 05689F
                       Gambar/Logo 143x116 
                       Text : E – PERPUS ( Font Inknut Antiqua, Size 40, Medium, Color Font FFFFFF, effect drop shadow disesuaikan)
                       Text : Nama Sekolah (Font Inknut Antiqua, Size 35,Regular, Color Font FFFFFF, effect drop shadow disesuaikan)
                       Text : Alamat,email,dll (Font Istok Web, Size 15, Regular, Color Font FFFFFF)

Rectangle 2 :  Uk. 859 x 481 (Radius 15)
		       Color : Biru Kode 05689F
Rectangle 3 : 37 x 43 (Radius 9) Color : Abu-abu Kode D9D9D9
Rectangle 4 : 357 x 43 Color Putih Kode FFFFFF
                      Gambar orang uk 25x26 
                      Text : Username (Font Archivo, Regular, 20 Color Hitam) Huruf menggunakan Underline
                      Effect Rectangle Drop Shadow
Rectangle 5 : 37 x 43 (Radius 9) Color : Abu-abu Kode D9D9D9
Rectangle 6 : 357 x 43 Color Putih Kode FFFFFF
                     Gambar Kunci 25 x 26  
                     Text : Password (Font Archivo, Regular, 20 Color Hitam) Huruf menggunakan Underline)
                     Gambar : mata uk 27 x 26
                     Effect Rectangle Drop Shadow
Rectangle 7 :  uk 13 x 15 Warna Putih (untuk Mengingat ceklis pada Menu Usr+psw) Effect Rectangle Drop Shadow

- Text Ingatkan Username dan Password (Font Arapey, Reguler, 20 Color hitam)
- Text Lupa Password (Font Arapey, Reguler, 20, Color Hitam)
- Texk Kilik Disini (Font Arapey, Reguler, 20, Color Biru Kode 0221BF)
- Text Belum Punya Akun (Font Archivo , Reguler , 20. Color Biru Kode 011AFF, Stoke 1 Putih)
- Text Daftar Disini (Font Archivo, Bold, 20 Color Hitam kode 060606)

- Retangle 8 : Uk 155 x 45 radius 10 Color Putih kode FFFFFF
                      Text : Masuk (Font Archivo, 20, Medium, Color Hitam kode 000000

Posisi rectangle 1 dan 2 ditengah, harus sama presisi, 
dan untuk rectangle username dan password itu mempunyai jarak 
Bila Font tidak ada sebaiknya menggunakan font yang percis sama

**Comment by Dhennuza** [comment]
inimah sudah saya kerjakan, tolong di cek, apakah sudah mirip, dan sudah sesuai
